### ISSUE TITLE
Issue with Android 10

### ISSUE THREAD

**Issue by athar92** [mhusseini/Xamarin.Bindings.Android.AwesomeImagePicker#1]
Hi! You have done a great job, i am using this library for quite some time but the problem is that i have just updated my xamarin app for android 10 and this library has stopped working, i have rebuild it with the source code for android 10 but it is not working. When clicked on the button to choose images, it shows empty tiles in pink color. Can you check the issue and help me with this? I love this library and don't want to change it. Will wait for your reply. Thanks in advance.
![Screenshot_2020-08-07-14-41-10-904_jo jocar 1](https://user-images.githubusercontent.com/69356979/89659318-26505580-d8e9-11ea-9f88-16b37fc74272.jpg)

**Comment by mhusseini** [comment]
Hi,

 

sorry to reply so late. The thing I that I haven’t used Xamarin for almost 3 years. The library isn’t from me, but from https://github.com/myinnos. All I did was to wrap it in a .net assembly. It seems the original author hasn’t updated the library for three years as well, so I’m not even sure that the original Java library works with Android 10. 

 

I’m deeply sorry that I couldn’t help you.

 

Best regards,

Munir
